### ISSUE TITLE
Modular Programming- p2p review

### ISSUE THREAD

**Issue by cindykandie** [Sammy3000/leaderboard-API#3]
**Hey @Sammy3000,**
🚀 Good Job!
🌸 Your code is clean and you have implemented your functions and actions correctly. Keep up!
Kindly consider splitting your javascript file into modules per function, this will help you greatly in future as you scale the application
🌸 Other than that, your code is quite clean. Congrats!

**Comment by Sammy3000** [comment]
- Thank you @cindykandie  for your feedback 👍 . Issue accepted and solved 😃 .
