### ISSUE TITLE
Peer to peer Review: Morning Session 10/02/2023

### ISSUE THREAD

**Issue by Donmark2k** [Sammy3000/leaderboard-API#5]
# Great Job @Sammy3000 

Hi @Sammy3000 , 
 

![](https://media1.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e471p9juygtcaesd615kgxa3b2n2dt6xyrzcycnk4b3&rid=giphy.gif&ct=g)

## Highlights

- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Meaningful commit messages ✔️
- correct github flow ✔️

## Optional Speech

- [ ] I would like to commend myself on a work well done. BRAVO

**Comment by Sammy3000** [comment]
- Thank you @Donmark2k  👍
